Skip to content
Sign up
brenomezencio
/
brenomezencio
Public
Code
Issues
Pull requests
1
Actions
Projects
More
https://github.com/BrenoMezencio/BrenoMezencio/edit/main/.github/workflows/cobrinha.yml
@brenomezencio
brenomezencio Create cobrinha.yml
 History
 1 contributor
25 lines (22 sloc)  583 Bytes
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: brenomezencio
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
